name: Build Docker R2 Image and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push the Docker image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 -t r2 --push .

      # 如果您需要保存镜像为 tar 文件，您需要单独构建每个平台
      - name: Save Docker image as tar (optional)
        run: |
          docker buildx build --platform linux/arm64 -t r2-arm64 --load .
          docker save r2-arm64 -o r2-arm64.tar
          docker buildx build --platform linux/amd64 -t r2-amd64 --load .
          docker save r2-amd64 -o r2-amd64.tar

      - name: Upload Docker image artifacts (optional)
        uses: actions/upload-artifact@latest
        with:
          name: r2-arm64
          path: r2-arm64.tar
          
      - name: Upload Docker image artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: r2-amd64
          path: r2-amd64.tar
